#!/bin/bash
# Regenerate the SDK's motionsense_defconfig from the vendor base plus the
# packages declared in buildroot-packages.fragment.
#
# Kept as an explicit step rather than a build hook: the buildroot defconfig
# is consumed early in the SDK's sysdrv stage, before any hook this app can
# register runs.
set -euo pipefail

HERE=$(cd "$(dirname "$(realpath "$0")")" && pwd)
APP_DIR=$(dirname "$HERE")
SDK_DIR=$(cd "$APP_DIR/../../.." && pwd)

FRAGMENT="$APP_DIR/buildroot-packages.fragment"
BASE="$SDK_DIR/sysdrv/tools/board/buildroot/luckfox_pico_defconfig"
OUT="$SDK_DIR/sysdrv/tools/board/buildroot/motionsense_defconfig"

[ -f "$BASE" ] || { echo "vendor defconfig not found: $BASE" >&2; exit 1; }
[ -f "$FRAGMENT" ] || { echo "fragment not found: $FRAGMENT" >&2; exit 1; }

# Strip comments and blanks from the fragment.
packages=$(grep -oE '^BR2_[A-Z0-9_]+=[ynm]' "$FRAGMENT" || true)
[ -n "$packages" ] || { echo "no BR2_ entries in $FRAGMENT" >&2; exit 1; }

{
    echo "# Generated by project/app/motionsense/scripts/gen-buildroot-defconfig.sh"
    echo "# Base: luckfox_pico_defconfig   Additions: buildroot-packages.fragment"
    echo "# Do not edit by hand; edit the fragment and re-run the script."
    cat "$BASE"
    echo
    echo "# --- declared by MotionSense ---"
    echo "$packages"
} > "$OUT"

echo "wrote $OUT"
echo "$packages" | sed 's/^/  + /'

# The SDK only copies defconfigs into buildroot when it first extracts it, so
# an already-extracted tree keeps using a stale copy without this.
BR_CONFIGS="$SDK_DIR/sysdrv/source/buildroot/buildroot-2023.02.6/configs"
if [ -d "$BR_CONFIGS" ]; then
    # Non-fatal: the extracted buildroot tree may be owned by another user
    # (it is created by the build, which often runs as root in a container).
    if cp "$OUT" "$BR_CONFIGS/" 2>/dev/null; then
        echo "also refreshed $BR_CONFIGS/motionsense_defconfig"
    else
        echo "WARNING: could not refresh $BR_CONFIGS/motionsense_defconfig" >&2
        echo "         the build will use a stale copy; re-run this script as" >&2
        echo "         the owner of that tree, or 'make buildroot_clean'." >&2
    fi
fi
